#!/bin/bash
###############################################################################
# shoefiles (bash script)
# This script handles installation of shoelick's dotfiles.
###############################################################################

main() {

    echo "Shoelick Dotfiles"
    echo "Updated November '16"

    export DEBUG_OUTPUT=1
    export DOTFILES_REPO_DIR="$( \cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    export DOTFILES_DIR="$HOME/.dotfiles"
    export DOTFILES_BACKUP=
    export SUBCMD=
    export TARGET=
    export PLATFORM=
    export ISGROUP=

    source "$DOTFILES_REPO_DIR/shoes/util.sh"
    source "$DOTFILES_REPO_DIR/shoes/parse_args.sh"
    source "$DOTFILES_REPO_DIR/shoes/shoes.conf"

    # Debug warning will show if above var is set
    Debug "Debugging is ON! To turn off, unset DEBUG_OUTPUT in shoefiles script."

    RetVal=0;

    #
    # Check args
    #
    Debug "Shoefiles received $@"
    AreArgsValid $@
    RetVal=$?

    # Exit if invalid usage
    [ $RetVal -gt $ERROR_CODE_NONE ] && PrintUsage && return $RetVal;
    
    #
    # Detect Platform
    #
    Debug "Entering platform check." 

    DetectPlatform
    RetVal=$?
    Debug "We are on $PLATFORM"
    # Exit if invalid 
    [ $RetVal -gt $ERROR_CODE_NONE ] && return $RetVal;

    #
    # Configure git
    #

    ## @todo set up .gitconfig


    #
    # Setup / check core
    #
    #source "$DOTFILES_REPO_DIR/core/${THIS_OS}.sh"

    #
    # Move dotfiles to final location
    #
    ConfigureDotfilesDir
    RetVal=$?
    [ $RetVal -gt $ERROR_CODE_NONE ] && return $RetVal;

    Debug "Entering command selection majigger"
    ## Execute appropriate action 
    case $SUBCMD in
        "install")
            Debug "Subcommand was $SUBCMD"
            ;;
        "update")
            Debug "Subcommand was $SUBCMD"
            ;;
        "uninstall")
            Debug "Subcommand was $SUBCMD"
            
            ;;
        "test")
            Debug "Subcommand was $SUBCMD"
            ;;
    esac

    return $RetVal

    #echo "Detected $THIS_OS. Lucky for you, $THIS_OS is supported."

    ## Perform update on dotfiles repo and submodules
    #if [ -d "${DOTFILES_DIR}/.git" ]; then
    #    git --work-tree="${DOTFILES_DIR}" --git-dir="${DOTFILES_DIR}/.git" pull \
    #        --recurse-submodules=yes origin master
    #    git submodule init
    #    git submodule update
    #fi

    ########################################
    ## Perform dotfiles toolbox setup
    ########################################

    ## Package options
    ## Provided packages:

    #if 
    #PACKAGES="zsh neovim"

    ## Source each installation script.
    #for PKG in $PACKAGES; do 
    #    PKG_CONFIG="${DOTFILES_DIR}/packages/${PKG}/config"
    #    source "./packages/${PKG}/${PKG}.sh"
    #    # Source package install script
    #    # All should include definitions for:
    #    # Install, Configure
    #
    #    Install
    #    if [[ $? -eq 0 ]]; then
    #        Configure
    #    else 
    #        echo "ERROR: Installation of $PKG failed."
    #    fi
    #    unset -f Install Configure
    #done    

} 

main $@
cd .
